/**
 * Database API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CollectionOptions model module.
* @module model/CollectionOptions
* @version 1.0.0
*/
export default class CollectionOptions {
    /**
    * Constructs a new <code>CollectionOptions</code>.
    * @alias module:model/CollectionOptions
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>CollectionOptions</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CollectionOptions} obj Optional instance to populate.
    * @return {module:model/CollectionOptions} The populated <code>CollectionOptions</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectionOptions();


            if (data.hasOwnProperty('asyncListeners')) {
                obj['asyncListeners'] = ApiClient.convertToType(data['asyncListeners'], 'Boolean');
            }
            if (data.hasOwnProperty('autoupdate')) {
                obj['autoupdate'] = ApiClient.convertToType(data['autoupdate'], 'Boolean');
            }
            if (data.hasOwnProperty('clone')) {
                obj['clone'] = ApiClient.convertToType(data['clone'], 'Boolean');
            }
            if (data.hasOwnProperty('disableChangesApi')) {
                obj['disableChangesApi'] = ApiClient.convertToType(data['disableChangesApi'], 'Boolean');
            }
            if (data.hasOwnProperty('disableDeltaChangesApi')) {
                obj['disableDeltaChangesApi'] = ApiClient.convertToType(data['disableDeltaChangesApi'], 'Boolean');
            }
            if (data.hasOwnProperty('disableFreeze')) {
                obj['disableFreeze'] = ApiClient.convertToType(data['disableFreeze'], 'Boolean');
            }
            if (data.hasOwnProperty('disableMeta')) {
                obj['disableMeta'] = ApiClient.convertToType(data['disableMeta'], 'Boolean');
            }
            if (data.hasOwnProperty('exact')) {
                obj['exact'] = ApiClient.convertToType(data['exact'], ['String']);
            }
            if (data.hasOwnProperty('indices')) {
                obj['indices'] = ApiClient.convertToType(data['indices'], ['String']);
            }
            if (data.hasOwnProperty('removeIndices')) {
                obj['removeIndices'] = ApiClient.convertToType(data['removeIndices'], 'Boolean');
            }
            if (data.hasOwnProperty('ttl')) {
                obj['ttl'] = ApiClient.convertToType(data['ttl'], 'Number');
            }
            if (data.hasOwnProperty('ttlInterval')) {
                obj['ttlInterval'] = ApiClient.convertToType(data['ttlInterval'], 'Number');
            }
            if (data.hasOwnProperty('unique')) {
                obj['unique'] = ApiClient.convertToType(data['unique'], ['String']);
            }
        }
        return obj;
    }



}
