/**
 * Database API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DynamicViewFilter from './DynamicViewFilter';
import DynamicViewOption from './DynamicViewOption';
import JsonObject from './JsonObject';
import SimpleCriteriaDto from './SimpleCriteriaDto';

/**
* The DynamicViewDto model module.
* @module model/DynamicViewDto
* @version 1.0.0
*/
export default class DynamicViewDto {
    /**
    * Constructs a new <code>DynamicViewDto</code>.
    * @alias module:model/DynamicViewDto
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>DynamicViewDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DynamicViewDto} obj Optional instance to populate.
    * @return {module:model/DynamicViewDto} The populated <code>DynamicViewDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DynamicViewDto();


            if (data.hasOwnProperty('filterPipeline')) {
                obj['filterPipeline'] = ApiClient.convertToType(data['filterPipeline'], [DynamicViewFilter]);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = DynamicViewOption.constructFromObject(data['options']);
            }
            if (data.hasOwnProperty('resultdata')) {
                obj['resultdata'] = ApiClient.convertToType(data['resultdata'], [JsonObject]);
            }
            if (data.hasOwnProperty('simpleCriteria')) {
                obj['simpleCriteria'] = SimpleCriteriaDto.constructFromObject(data['simpleCriteria']);
            }
            if (data.hasOwnProperty('sortCriteria')) {
                obj['sortCriteria'] = ApiClient.convertToType(data['sortCriteria'], [SimpleCriteriaDto]);
            }
        }
        return obj;
    }


}
