/**
 * Database API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Health model module.
* @module model/Health
* @version 1.0.0
*/
export default class Health {
    /**
    * Constructs a new <code>Health</code>.
    * @alias module:model/Health
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>Health</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Health} obj Optional instance to populate.
    * @return {module:model/Health} The populated <code>Health</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Health();


            if (data.hasOwnProperty('nbDatabases')) {
                obj['nbDatabases'] = ApiClient.convertToType(data['nbDatabases'], 'Number');
            }
            if (data.hasOwnProperty('up')) {
                obj['up'] = ApiClient.convertToType(data['up'], 'Boolean');
            }
        }
        return obj;
    }




}
