/**
 * Database API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The JsonObject model module.
* @module model/JsonObject
* @version 1.0.0
*/
export default class JsonObject {
    /**
    * Constructs a new <code>JsonObject</code>.
    * @alias module:model/JsonObject
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>JsonObject</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/JsonObject} obj Optional instance to populate.
    * @return {module:model/JsonObject} The populated <code>JsonObject</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JsonObject();


            if (data.hasOwnProperty('map')) {
                obj['map'] = ApiClient.convertToType(data['map'], 'Object');
            }
            if (data.hasOwnProperty('empty')) {
                obj['empty'] = ApiClient.convertToType(data['empty'], 'Boolean');
            }
        }
        return obj;
    }



}
