/**
 * Database API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CollectionDto from './CollectionDto';

/**
* The ListCollectionDto model module.
* @module model/ListCollectionDto
* @version 1.0.0
*/
export default class ListCollectionDto extends Array {
    /**
    * Constructs a new <code>ListCollectionDto</code>.
    * @alias module:model/ListCollectionDto
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>ListCollectionDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ListCollectionDto} obj Optional instance to populate.
    * @return {module:model/ListCollectionDto} The populated <code>ListCollectionDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListCollectionDto();
            ApiClient.constructFromObject(data, obj, 'CollectionDto');
            
            
        }
        return obj;
    }





}
