/**
 * Database API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ListCollectionDto from './ListCollectionDto';
import ThorOptions from './ThorOptions';

/**
* The ThorDto model module.
* @module model/ThorDto
* @version 1.0.0
*/
export default class ThorDto {
    /**
    * Constructs a new <code>ThorDto</code>.
    * @alias module:model/ThorDto
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>ThorDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ThorDto} obj Optional instance to populate.
    * @return {module:model/ThorDto} The populated <code>ThorDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThorDto();


            if (data.hasOwnProperty('autosave')) {
                obj['autosave'] = ApiClient.convertToType(data['autosave'], 'Boolean');
            }
            if (data.hasOwnProperty('autosaveHandle')) {
                obj['autosaveHandle'] = ApiClient.convertToType(data['autosaveHandle'], 'Number');
            }
            if (data.hasOwnProperty('autosaveInterval')) {
                obj['autosaveInterval'] = ApiClient.convertToType(data['autosaveInterval'], 'Number');
            }
            if (data.hasOwnProperty('collections')) {
                obj['collections'] = ListCollectionDto.constructFromObject(data['collections']);
            }
            if (data.hasOwnProperty('databaseVersion')) {
                obj['databaseVersion'] = ApiClient.convertToType(data['databaseVersion'], 'Number');
            }
            if (data.hasOwnProperty('engineVersion')) {
                obj['engineVersion'] = ApiClient.convertToType(data['engineVersion'], 'Number');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ThorOptions.constructFromObject(data['options']);
            }
        }
        return obj;
    }




}
