/**
 * Database API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JsonObject from './JsonObject';

/**
* The TransformDto model module.
* @module model/TransformDto
* @version 1.0.0
*/
export default class TransformDto {
    /**
    * Constructs a new <code>TransformDto</code>.
    * @alias module:model/TransformDto
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>TransformDto</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TransformDto} obj Optional instance to populate.
    * @return {module:model/TransformDto} The populated <code>TransformDto</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransformDto();


            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('operations')) {
                obj['operations'] = ApiClient.convertToType(data['operations'], [JsonObject]);
            }
        }
        return obj;
    }



}
