/**
 * Database API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Ttl model module.
* @module model/Ttl
* @version 1.0.0
*/
export default class Ttl {
    /**
    * Constructs a new <code>Ttl</code>.
    * @alias module:model/Ttl
    * @class
    */

    constructor() {



    }

    /**
    * Constructs a <code>Ttl</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Ttl} obj Optional instance to populate.
    * @return {module:model/Ttl} The populated <code>Ttl</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Ttl();


            if (data.hasOwnProperty('age')) {
                obj['age'] = ApiClient.convertToType(data['age'], 'Number');
            }
            if (data.hasOwnProperty('daemon')) {
                obj['daemon'] = ApiClient.convertToType(data['daemon'], 'Number');
            }
            if (data.hasOwnProperty('ttlInterval')) {
                obj['ttlInterval'] = ApiClient.convertToType(data['ttlInterval'], 'Number');
            }
        }
        return obj;
    }




}
