/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package fr.genin.christophe.thor.core.serialization.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroTransform extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4554940343596287182L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroTransform\",\"namespace\":\"fr.genin.christophe.thor.core.serialization.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"operations\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroTransform> ENCODER =
      new BinaryMessageEncoder<AvroTransform>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroTransform> DECODER =
      new BinaryMessageDecoder<AvroTransform>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroTransform> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroTransform> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroTransform> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroTransform>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroTransform to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroTransform from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroTransform instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroTransform fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence name;
   private java.util.List<java.lang.CharSequence> operations;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroTransform() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param operations The new value for operations
   */
  public AvroTransform(java.lang.CharSequence name, java.util.List<java.lang.CharSequence> operations) {
    this.name = name;
    this.operations = operations;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return operations;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: operations = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'operations' field.
   * @return The value of the 'operations' field.
   */
  public java.util.List<java.lang.CharSequence> getOperations() {
    return operations;
  }


  /**
   * Sets the value of the 'operations' field.
   * @param value the value to set.
   */
  public void setOperations(java.util.List<java.lang.CharSequence> value) {
    this.operations = value;
  }

  /**
   * Creates a new AvroTransform RecordBuilder.
   * @return A new AvroTransform RecordBuilder
   */
  public static fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder newBuilder() {
    return new fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder();
  }

  /**
   * Creates a new AvroTransform RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroTransform RecordBuilder
   */
  public static fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder newBuilder(fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder other) {
    if (other == null) {
      return new fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder();
    } else {
      return new fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder(other);
    }
  }

  /**
   * Creates a new AvroTransform RecordBuilder by copying an existing AvroTransform instance.
   * @param other The existing instance to copy.
   * @return A new AvroTransform RecordBuilder
   */
  public static fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder newBuilder(fr.genin.christophe.thor.core.serialization.avro.AvroTransform other) {
    if (other == null) {
      return new fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder();
    } else {
      return new fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroTransform instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroTransform>
    implements org.apache.avro.data.RecordBuilder<AvroTransform> {

    private java.lang.CharSequence name;
    private java.util.List<java.lang.CharSequence> operations;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.operations)) {
        this.operations = data().deepCopy(fields()[1].schema(), other.operations);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroTransform instance
     * @param other The existing instance to copy.
     */
    private Builder(fr.genin.christophe.thor.core.serialization.avro.AvroTransform other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.operations)) {
        this.operations = data().deepCopy(fields()[1].schema(), other.operations);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'operations' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getOperations() {
      return operations;
    }


    /**
      * Sets the value of the 'operations' field.
      * @param value The value of 'operations'.
      * @return This builder.
      */
    public fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder setOperations(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.operations = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'operations' field has been set.
      * @return True if the 'operations' field has been set, false otherwise.
      */
    public boolean hasOperations() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'operations' field.
      * @return This builder.
      */
    public fr.genin.christophe.thor.core.serialization.avro.AvroTransform.Builder clearOperations() {
      operations = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroTransform build() {
      try {
        AvroTransform record = new AvroTransform();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.operations = fieldSetFlags()[1] ? this.operations : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroTransform>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroTransform>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroTransform>
    READER$ = (org.apache.avro.io.DatumReader<AvroTransform>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    long size0 = this.operations.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.operations) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.operations;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("operations").schema());
        this.operations = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.operations;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("operations").schema());
            this.operations = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










