/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package fr.genin.christophe.thor.core.serialization.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroThor extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8466215877864571907L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroThor\",\"namespace\":\"fr.genin.christophe.thor.core.serialization.avro\",\"fields\":[{\"name\":\"collections\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroCollection\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]},{\"name\":\"binaryIndices\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]},{\"name\":\"uniques\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]},{\"name\":\"exacts\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]},{\"name\":\"transforms\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroTransform\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"operations\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]}]}},\"default\":[]},{\"name\":\"dynamicViews\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroDynamicView\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"filterPipeline\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroDynamicViewFilter\",\"fields\":[{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"val\",\"type\":\"string\"},{\"name\":\"uid\",\"type\":\"string\"}]}},\"default\":[]}]}},\"default\":[]}]}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroThor> ENCODER =
      new BinaryMessageEncoder<AvroThor>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroThor> DECODER =
      new BinaryMessageDecoder<AvroThor>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroThor> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroThor> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroThor> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroThor>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroThor to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroThor from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroThor instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroThor fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> collections;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroThor() {}

  /**
   * All-args constructor.
   * @param collections The new value for collections
   */
  public AvroThor(java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> collections) {
    this.collections = collections;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return collections;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: collections = (java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'collections' field.
   * @return The value of the 'collections' field.
   */
  public java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> getCollections() {
    return collections;
  }


  /**
   * Sets the value of the 'collections' field.
   * @param value the value to set.
   */
  public void setCollections(java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> value) {
    this.collections = value;
  }

  /**
   * Creates a new AvroThor RecordBuilder.
   * @return A new AvroThor RecordBuilder
   */
  public static fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder newBuilder() {
    return new fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder();
  }

  /**
   * Creates a new AvroThor RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroThor RecordBuilder
   */
  public static fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder newBuilder(fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder other) {
    if (other == null) {
      return new fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder();
    } else {
      return new fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder(other);
    }
  }

  /**
   * Creates a new AvroThor RecordBuilder by copying an existing AvroThor instance.
   * @param other The existing instance to copy.
   * @return A new AvroThor RecordBuilder
   */
  public static fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder newBuilder(fr.genin.christophe.thor.core.serialization.avro.AvroThor other) {
    if (other == null) {
      return new fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder();
    } else {
      return new fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroThor instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroThor>
    implements org.apache.avro.data.RecordBuilder<AvroThor> {

    private java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> collections;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.collections)) {
        this.collections = data().deepCopy(fields()[0].schema(), other.collections);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroThor instance
     * @param other The existing instance to copy.
     */
    private Builder(fr.genin.christophe.thor.core.serialization.avro.AvroThor other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.collections)) {
        this.collections = data().deepCopy(fields()[0].schema(), other.collections);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'collections' field.
      * @return The value.
      */
    public java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> getCollections() {
      return collections;
    }


    /**
      * Sets the value of the 'collections' field.
      * @param value The value of 'collections'.
      * @return This builder.
      */
    public fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder setCollections(java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> value) {
      validate(fields()[0], value);
      this.collections = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'collections' field has been set.
      * @return True if the 'collections' field has been set, false otherwise.
      */
    public boolean hasCollections() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'collections' field.
      * @return This builder.
      */
    public fr.genin.christophe.thor.core.serialization.avro.AvroThor.Builder clearCollections() {
      collections = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroThor build() {
      try {
        AvroThor record = new AvroThor();
        record.collections = fieldSetFlags()[0] ? this.collections : (java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroThor>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroThor>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroThor>
    READER$ = (org.apache.avro.io.DatumReader<AvroThor>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.collections.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (fr.genin.christophe.thor.core.serialization.avro.AvroCollection e0: this.collections) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> a0 = this.collections;
      if (a0 == null) {
        a0 = new SpecificData.Array<fr.genin.christophe.thor.core.serialization.avro.AvroCollection>((int)size0, SCHEMA$.getField("collections").schema());
        this.collections = a0;
      } else a0.clear();
      SpecificData.Array<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<fr.genin.christophe.thor.core.serialization.avro.AvroCollection>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          fr.genin.christophe.thor.core.serialization.avro.AvroCollection e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new fr.genin.christophe.thor.core.serialization.avro.AvroCollection();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> a0 = this.collections;
          if (a0 == null) {
            a0 = new SpecificData.Array<fr.genin.christophe.thor.core.serialization.avro.AvroCollection>((int)size0, SCHEMA$.getField("collections").schema());
            this.collections = a0;
          } else a0.clear();
          SpecificData.Array<fr.genin.christophe.thor.core.serialization.avro.AvroCollection> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<fr.genin.christophe.thor.core.serialization.avro.AvroCollection>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              fr.genin.christophe.thor.core.serialization.avro.AvroCollection e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new fr.genin.christophe.thor.core.serialization.avro.AvroCollection();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










